apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-sales-api-config
  namespace: vehicle-sales
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Keycloak__Authority: https://keycloak.example.com/realms/fiap-vehicle-sales
  Keycloak__MetadataAddress: https://keycloak.example.com/realms/fiap-vehicle-sales/.well-known/openid-configuration
  Keycloak__Audience: vehicle-sales-api
