apiVersion: v1
kind: Secret
metadata:
  name: vehicle-sales-secrets
  namespace: vehicle-sales
type: Opaque
stringData:
  postgres-database: vehicle_sales_db
  postgres-username: vehicle_sales
  postgres-password: CHANGE_ME
  connection-string: Host=vehicle-sales-db;Port=5432;Database=vehicle_sales_db;Username=vehicle_sales;Password=CHANGE_ME
